name: quick_mart
description: A Flutter e-commerce app with a modern home screen UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  google_fonts: ^6.1.0
  file_picker: ^8.1.2
  http: ^1.1.0
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

